/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 worms-transformed.glb --types
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    noodle_1: THREE.Mesh
    noodle_2: THREE.Mesh
    noodle_3: THREE.Mesh
    noodle_4: THREE.Mesh
  }
  materials: {}
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/worms-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.noodle_1.geometry} material={nodes.noodle_1.material} />
      <mesh geometry={nodes.noodle_2.geometry} material={nodes.noodle_2.material} />
      <mesh geometry={nodes.noodle_3.geometry} material={nodes.noodle_3.material} />
      <mesh geometry={nodes.noodle_4.geometry} material={nodes.noodle_4.material} />
    </group>
  )
}

useGLTF.preload('/worms-transformed.glb')
